channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.2
- pip:
  - mlflow==2.17.2
  - scikit-learn==1.5.2
  - pandas==2.2.3
  - numpy==2.1.1
  - xgboost==2.1.1
  - keras==3.6.0
  - jax[cpu]==0.4.35
name: mlflow-env
